name: Run tests on PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Run tests and linting
        run: |
          npm i -g lerna
          lerna bootstrap
          lerna run build
          npm test
        env:
          CI: true

